# Generated by Django 2.0.5 on 2018-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email', max_length=255),
            preserve_default=False,
        ),
    ]
